/**:
  robotnik_charge:
    ros__parameters:
      rate: 10
      fixed_frame: "robot_odom"
      step_timeout: 30.0
      timeout_charging_detection: 5
      charge_contact_distance_from_marker: 0.105
      has_safety_lasers: false
      laser_mode_during_action: "charging_station"
      laser_mode_after_action: "standard"
      step_back_distance: 0.5
      rotation: 0.0
      dock:
        action_namespace: "accurate_smooth_dock/dock"
        max_velocity:
          x: 0.1
          y: 0.1
          yaw: 0.1
      move:
        action_namespace: "move"
        max_velocity:
          x: 0.1
          y: 0.1
          yaw: 0.1

      # marker
      # offset X
      # predock_offset
      # final_approach_vel_x:
      # timeout robot_moving: tbd
      # str: stop_condition: position, (magnetic_field, motor_current), ...
